=== kayanrae/factura/TEMA 3/factura.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT FACTURA (TITLE,BODY)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT BODY (B1,B2,PRODUSE_COMANDATE,B3)>
<!ELEMENT B1 (SERIE, date)>
<!ELEMENT SERIE (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT B2 (FIRMA,CLIENT)>
<!ELEMENT FIRMA (TITLE,CIF,ADRESS,IBANNR,NAME_BANCA)>
<!ELEMENT CIF (#PCDATA)>
<!ELEMENT ADRESS (#PCDATA)>
<!ELEMENT IBANNR (#PCDATA)>
<!ELEMENT NAME_BANCA (#PCDATA)>
<!ELEMENT PRODUSE_COMANDATE (PRODUS*, TOTAL_FACTURA)>
<!ELEMENT PRODUS (NAME,MASURA,CANTITATE,PRET_FARA_TVA,VAL_TVA,PRET_TOTAL)>
<!ATTLIST PRODUS id CDATA #REQUIRED>
<!ELEMENT MASURA (#PCDATA)>
<!ELEMENT CANTITATE (#PCDATA)>
<!ELEMENT PRET_FARA_TVA (#PCDATA)>
<!ELEMENT VAL_TVA (#PCDATA)>
<!ELEMENT PRET_TOTAL (#PCDATA)>
<!ELEMENT TOTAL_FACTURA (TOTAL_FARA_TVA,TOTAL_VAL_TVA,PRET_TOTAL)>
<!ELEMENT TOTAL_FARA_TVA (#PCDATA)>
<!ELEMENT TOTAL_VAL_TVA (#PCDATA)>
<!ELEMENT B3 (NAME_REDACTOR,CNP,NAME_DELEGAT,MIJLOC_TRANSPORT)>
<!ELEMENT NAME_REDACTOR (#PCDATA)>
<!ELEMENT CNP (#PCDATA)>
<!ELEMENT NAME_DELEGAT (#PCDATA)>
<!ELEMENT MIJLOC_TRANSPORT (#PCDATA)>

=== kayanrae/factura/TEMA 3/factura-validare-dtd.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE FACTURA SYSTEM "factura.dtd">

<FACTURA>
   <TITLE>Firma de proba</TITLE>
   <BODY>
      <B1>
         <SERIE>FCT. nr.0023</SERIE>
         <date type="date">2008-03-27</date>
      </B1>
      <B2>
         <FIRMA>
            <TITLE>Firma Test</TITLE>
            <CIF>RO123456678</CIF>
            <ADRESS>Str.Bucuresti,nr.22,Craiova,Jud.Dolj</ADRESS>
            <IBANNR>RO1234567890111213141516</IBANNR>
            <NUME_BANCA>BCR.Craiova</NUME_BANCA>
         </FIRMA>
         <CLIENT>
            <NUME>Dynamic Soft Service</NUME>
            <CIF>RO5566778889</CIF>
            <ADRESS>str.Client,nr.5,Brasov, jud. Brasov</ADRESS>
            <IBANNR>RO01BTRL6567858XXXXXXXXX</IBANNR>
            <NUME_BANCA>BT.Brasov</NUME_BANCA>
         </CLIENT>
      </B2>
      <PRODUSE_COMANDATE>
         <PRODUS id="1">
            <NUME>Prestari servicii contact nr.21/14.01.2008</NUME>
            <MASURA>Bucata</MASURA>
            <CANTITATE>1 Bucata</CANTITATE>
            <PRET_FARA_TVA>1000</PRET_FARA_TVA>
            <VAL_TVA>190</VAL_TVA>
            <PRET_TOTAL>1190</PRET_TOTAL>
         </PRODUS>
         <PRODUS id="2">
            <NUME>Hosting server</NUME>
            <MASURA>saptamani</MASURA>
            <CANTITATE>50</CANTITATE>
            <PRET_FARA_TVA>5000</PRET_FARA_TVA>
            <VAL_TVA>950</VAL_TVA>
            <PRET_TOTAL>5950</PRET_TOTAL>
         </PRODUS>
         <PRODUS id="3">
            <NUME>Dezvoltare aplicatie mobila</NUME>
            <MASURA>Bucata</MASURA>
            <CANTITATE>1 Bucata</CANTITATE>
            <PRET_FARA_TVA>3000</PRET_FARA_TVA>
            <VAL_TVA>570</VAL_TVA>
            <PRET_TOTAL>3570</PRET_TOTAL>
         </PRODUS>
         <TOTAL_FACTURA>
            <TOTAL_FARA_TVA>9000</TOTAL_FARA_TVA>
            <TOTAL_VAL_TVA>1710</TOTAL_VAL_TVA>
            <TOTAL>10710</TOTAL>
         </TOTAL_FACTURA>
      </PRODUSE_COMANDATE>
      <B3>
         <NUME_REDACTOR_FACTURA>Vlaicu Pop</NUME_REDACTOR_FACTURA>
         <CNP>18212201904565</CNP>
         <NUME_DELEGAT>Maria Voda</NUME_DELEGAT>
         <MIJLOC_TRANSPORT>B43833</MIJLOC_TRANSPORT>
      </B3>
   </BODY>
</FACTURA>
